name: banas_dairy
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  email_validator: null
  google_fonts:

  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  get: null
  pinput: ^1.2.0
  url_launcher: null

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/banas logo.png"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # OLD CODE OF ASSETS
  #   - assets/images/logo.png
  #   - assets/images/splash.png
  #   - assets/images/bottomimg.png
  #   - assets/images/topimg.png
  #   - assets/images/background.png
  #   - assets/images/img.png
  #   - assets/images/topimagenew.png
  #   - assets/images/logonew.png
  #   - assets/images/back.png
  #   - assets/images/customer.png
  #   - assets/images/employee.png
  #   - assets/images/society.png
  #   - assets/images/farmer.png
  #   - assets/images/Rectangle.png
  #   - assets/images/top.png
  #   - assets/images/banas logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # - family: Schyler
  # - fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  # - family: Trajan Pro
  # - fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  # - family: OpenSans
  # - fonts:
  #     - assets: fonts/OpenSans.ttf
  #     - assets: fonts/OpenSans-Italic.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
